name: git push into another repo to deploy to vercel develop

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Check output directory
        run: |
          if [ -d "output" ]; then
            echo "Output directory exists"
          else
            echo "Output directory does not exist"
            exit 1
          fi
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: futureplanning
          destination-repository-name: homepage
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
